# Generated by Django 5.0.3 on 2024-06-03 22:23

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_agenda', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='imagens_equipe/')),
                ('cargo', models.CharField(max_length=200)),
                ('biografia', ckeditor_uploader.fields.RichTextUploadingField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(blank=True, max_length=100)),
                ('resumo', models.TextField()),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateField()),
                ('autores_equipe', models.ManyToManyField(blank=True, to='myapp.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_plantas/')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='myapp.planta')),
            ],
            options={
                'verbose_name_plural': 'Imagens Planta',
            },
        ),
        migrations.CreateModel(
            name='CoordenadaPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_x', models.FloatField()),
                ('posicao_y', models.FloatField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='myapp.planta')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Planta',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='imagens_postagens/')),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('autor_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipe')),
            ],
            options={
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
