# Generated by Django 4.2.6 on 2023-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(max_length=100)),
                ('imagens', models.ImageField(upload_to='imagens_plantas/')),
                ('resumo', models.TextField()),
                ('texto', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
    ]
