# Generated by Django 4.2.6 on 2023-12-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_atividade_mensagem_postagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
