# Generated by Django 4.2.6 on 2024-01-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='imagens',
        ),
        migrations.CreateModel(
            name='ImagemPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_plantas/')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='myapp.planta')),
            ],
        ),
    ]
