# Generated by Django 4.2.6 on 2024-01-27 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_imagemplanta_tags_planta_posicao_x_planta_posicao_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='resumo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='planta',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
