# Generated by Django 4.2.6 on 2024-01-27 05:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_atividade_descricao_alter_planta_resumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_equipe/')),
                ('cargo', models.CharField(max_length=200)),
                ('bibliografia', ckeditor.fields.RichTextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='autor',
        ),
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_postagens/'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='autor_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipe'),
        ),
    ]
