# Generated by Django 4.2.6 on 2024-01-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_equipe_remove_postagem_autor_postagem_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='participantes',
        ),
        migrations.AddField(
            model_name='atividade',
            name='autor_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.equipe'),
        ),
    ]
