# Generated by Django 4.2.6 on 2024-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_atividade_participantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='autor_equipe',
        ),
        migrations.AddField(
            model_name='atividade',
            name='autores_equipe',
            field=models.ManyToManyField(blank=True, to='myapp.equipe'),
        ),
    ]
