# Generated by Django 4.2.6 on 2024-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_atividade_autor_equipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_agenda', models.BooleanField(default=True)),
            ],
        ),
    ]
