# Generated by Django 4.2.6 on 2024-02-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_inscrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='nome',
            new_name='assunto',
        ),
    ]
