# Generated by Django 4.2.6 on 2024-03-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_nome_mensagem_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='link',
        ),
    ]
