# Generated by Django 4.2.6 on 2024-03-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_planta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemplanta',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
