# Generated by Django 5.0.3 on 2024-03-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_atividade_descricao_alter_equipe_bibliografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='bibliografia',
            new_name='biografia',
        ),
    ]
