# Generated by Django 5.0.1 on 2024-04-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_planta_posicao_x_remove_planta_posicao_y_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordenada',
            new_name='CoordenadaPlanta',
        ),
    ]
