# Generated by Django 5.0.3 on 2024-04-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_coordenada_coordenadaplanta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='coordenadaplanta',
            options={'verbose_name_plural': 'Coordenadas Planta'},
        ),
        migrations.AlterModelOptions(
            name='imagemplanta',
            options={'verbose_name_plural': 'Imagens Planta'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterField(
            model_name='coordenadaplanta',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='myapp.planta'),
        ),
    ]
