# Generated by Django 5.0.3 on 2024-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_atividade_imagem_alter_equipe_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
